#ifndef APX_CFG_H
#define APX_CFG_H

#define APX_BUF_GROW_SIZE 65536
#define APX_MAX_NAME_LEN 256
#define APX_MAX_PSG_LEN 1024
#define APX_DEFAULT_THREAD_STACK_SIZE 0x100000 //1MB

#endif //APX_CFG_H
